### ISSUE TITLE
No controller to clear the fields from outside the widget

### ISSUE THREAD

**Issue by Charlinjoeaht** [mincheol-shin/scroll_date_picker#1]
Once the widget is created with default value, then the only way to change value is to open the dialog and select a new value. The value shall be able to be controlled in the place where it is used

**Comment by mincheol-shin** [comment]
Thank you for writing your opinion! 

We are working to sort this out and will roll out a fix as soon as possible.

Thank you.

**Comment by mincheol-shin** [comment]
We added the function and proceeded with the 2.0.4 update.
