### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by jhyoon99** [mincheol-shin/scroll_date_picker#10]
../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/scroll_date_picker-3.5.0/lib/src/scroll_date_picker.dart:122:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
      

A warning message is printed.
Thanks for solving it.

**Comment by mincheol-shin** [comment]
We will fix it by referring to the flutter 3.0.0 release notes.

thank you :)

**Comment by mincheol-shin** [comment]
We have removed the issue you have written and updated 3.5.1 

Thank you :)
