### ISSUE TITLE
ontap 이나 gesture 를 통해 날짜를 직접 선택하는 기능은 없을까요?

### ISSUE THREAD

**Issue by unyang09** [mincheol-shin/scroll_date_picker#28]
만약 2000년에 위치 하고 있는데 1998년을 세밀히 움직이기가 힘든 유저를 위해 희미히 보이는 1998을 탭 할 시 1998로 이동하는 기능을 원합니다

**Comment by mincheol-shin** [comment]
좋은 의견 남겨 주셔서 감사합니다!
해당 기능을 지원할 수 있도록 개발해보도록 하겠습니다.
감사합니다!

**Comment by mincheol-shin** [comment]
Your input is appreciated!
We have added the feature and proceeded with the 3.8.0 update.
Thank you.
