### ISSUE TITLE
large text overflows

### ISSUE THREAD

**Issue by danbeechbloom** [mincheol-shin/scroll_date_picker#30]
When the font scale factor is set to a large size some of the dates overflow the width, causing the year to truncate.

If anybody else has this issue you can solve it by wrapping the ScrollDatePicker with a MediaQuery widget with the below prop:
```dart
textScaler: const TextScaler.linear(1.0) // To set a value

// OR

textScaler: TextScaler.noScaling // Don't allow text scaling
```

Might be worth adding an optional min/max text scale factor to the `ScrollViewOptions` to apply to the text/textspan widgets?

Thanks! 🫶

**Comment by mincheol-shin** [comment]
Thank you for the great suggestion. I anticipate that it would be better to rely on support from the package rather than configuring it within the project. We will proceed with package updates by providing relevant options.

**Comment by GalaxyTea1** [comment]
yep, I get the same error, but I don't know add textScaler where in code? And can I custom style text datetime where @danbeechbloom ? Thank you.

**Comment by GalaxyTea1** [comment]
yep, I get a same error, but I try textScaler not fix it.

**Comment by GalaxyTea1** [comment]
I get a same error, but I use <code>label: ' '</code> fix it. 😄
