### ISSUE TITLE
viewType issue

### ISSUE THREAD

**Issue by mkhitar-avsharyan** [mincheol-shin/scroll_date_picker#36]
When in viewType we have month and year and changing month or year getting error like this
`FixedExtentScrollController.selectedItem cannot be accessed before a scroll view is built with it.
'package:flutter/src/widgets/list_wheel_scroll_view.dart':
Failed assertion: line 241 pos 7: 'positions.isNotEmpty'`

**Comment by mincheol-shin** [comment]
Your input is appreciated!
We have added the feature and proceeded with the 3.7.4 update.
Thank you.
